#!/usr/bin/env bash
# EldritchDM — docker compose smoke test (DEPLOY-03).
#
# Operator-opt-in regression check for the bundled docker stack. NOT wired
# into default CI — assumes a working Docker daemon and the compose v2 plugin
# (`docker compose`). On a fresh machine, run after every Dockerfile or
# docker-compose.yml change:
#
#   bash scripts/ops/test_docker_smoke.sh
#
# What it does:
#   1. Preflights `docker` + `docker compose` availability (exit 2 if missing).
#   2. Builds the `eldritch-bot` image.
#   3. Brings up the stack with a throwaway `.env.smoke` if no real .env exists
#      (the smoke probe runs before the bot's Discord login, so a fake token
#      is safe — the bot never actually phones home).
#   4. Execs `python -c 'import eldritch_dm'` inside the container — proves
#      the venv + source survived the multi-stage build.
#   5. Reports the image size and WARNs (does not fail) if >500 MiB.
#   6. Always tears the stack down on exit, including the named volume.
#
# Exit codes:
#   0  smoke pass
#   1  smoke fail (build, up, exec, or down)
#   2  docker / compose v2 not installed (preflight)

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Resolve repo root from this script's location — works regardless of cwd.
# ─────────────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

SERVICE="eldritch-bot"
IMAGE="eldritch-dm:local"
IMAGE_SIZE_WARN_BYTES=$((500 * 1024 * 1024))   # 500 MiB

# ─────────────────────────────────────────────────────────────────────────────
# Logging helpers — keep output greppable.
# ─────────────────────────────────────────────────────────────────────────────
log()  { printf '\033[1;36m[smoke]\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[1;33m[smoke WARN]\033[0m %s\n' "$*" >&2; }
err()  { printf '\033[1;31m[smoke FAIL]\033[0m %s\n' "$*" >&2; }

# ─────────────────────────────────────────────────────────────────────────────
# Preflight — exit 2 (distinct from generic failure) when tooling is missing,
# so CI / wrappers can tell "Docker not installed" apart from "test failed".
# ─────────────────────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  err "'docker' not found on PATH. Install Docker Desktop or Engine first."
  exit 2
fi

if ! docker compose version >/dev/null 2>&1; then
  err "'docker compose' (v2 plugin) not available. This script requires the"
  err "compose v2 CLI plugin — 'docker-compose' v1 is not supported."
  exit 2
fi

log "docker:         $(docker --version)"
log "docker compose: $(docker compose version --short 2>/dev/null || docker compose version | head -1)"

# ─────────────────────────────────────────────────────────────────────────────
# Cleanup trap — runs on success, failure, or interrupt. Always idempotent.
# ─────────────────────────────────────────────────────────────────────────────
cleanup() {
  local rc=$?
  if [ $rc -ne 0 ] && [ $rc -ne 2 ]; then
    err "smoke test failed (exit $rc) — dumping container logs:"
    docker compose logs "$SERVICE" 2>&1 | tail -50 >&2 || true
  fi
  log "tearing down compose stack…"
  docker compose down -v --remove-orphans >/dev/null 2>&1 || true
  if [ "${CREATED_DOT_ENV:-0}" -eq 1 ] && [ -f .env ]; then
    rm -f .env
  fi
  exit $rc
}
trap cleanup EXIT INT TERM

# ─────────────────────────────────────────────────────────────────────────────
# Stub .env for the build + up cycle if the operator hasn't created one.
# The smoke probe runs `import eldritch_dm` and exits before bot.run, so the
# placeholder DISCORD_TOKEN never reaches Discord's auth endpoint.
# ─────────────────────────────────────────────────────────────────────────────
CREATED_DOT_ENV=0
if [ ! -f .env ]; then
  log "no .env at repo root — writing throwaway .env for the smoke cycle"
  cat > .env <<'EOF'
# Auto-generated by scripts/ops/test_docker_smoke.sh — safe to delete.
# The smoke probe runs `import eldritch_dm` and exits before bot.run, so this
# placeholder token never reaches Discord's auth endpoint.
DISCORD_TOKEN=smoke-test-not-a-real-token
EOF
  CREATED_DOT_ENV=1
fi

# ─────────────────────────────────────────────────────────────────────────────
# Build → up → exec → size-check. Each step logs its intent so a failure has
# obvious context in the operator's terminal.
# ─────────────────────────────────────────────────────────────────────────────
log "building image $IMAGE…"
docker compose build "$SERVICE"

log "starting $SERVICE in the background…"
docker compose up -d "$SERVICE"

log "waiting up to 60s for the container to be running…"
deadline=$(( $(date +%s) + 60 ))
while :; do
  state=$(docker inspect --format '{{.State.Status}}' eldritch_bot 2>/dev/null || echo "missing")
  case "$state" in
    running) log "container is running"; break ;;
    exited|dead|missing)
      err "container is in state '$state' before probe could run"
      exit 1
      ;;
  esac
  if [ "$(date +%s)" -ge "$deadline" ]; then
    err "timeout waiting for container to be running (last state: $state)"
    exit 1
  fi
  sleep 1
done

log "probing: import eldritch_dm inside the container…"
probe_output=$(docker compose exec -T "$SERVICE" \
  python -c "import eldritch_dm; print('OK:', eldritch_dm.__name__)")
log "probe output: $probe_output"
if ! printf '%s' "$probe_output" | grep -q '^OK:'; then
  err "probe did not return 'OK:' — got: $probe_output"
  exit 1
fi

log "checking image size budget (warn-only)…"
size_bytes=$(docker image inspect "$IMAGE" --format '{{.Size}}' 2>/dev/null || echo 0)
size_mib=$(( size_bytes / 1024 / 1024 ))
log "image size: ${size_mib} MiB"
if [ "$size_bytes" -gt "$IMAGE_SIZE_WARN_BYTES" ]; then
  warn "image is larger than 500 MiB budget (D-223). Investigate before tagging a release."
fi

log "smoke test PASSED ✔"
# trap cleanup() will tear the stack down and exit 0.
